import type { Metadata } from 'next';
import { AuthenticationContextProvider } from '../contexts/AuthenticationContext';
import { AlertContextProvider } from '@/contexts/AlertContext';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={''}>
        <AuthenticationContextProvider>
          <AlertContextProvider>{children}</AlertContextProvider>
        </AuthenticationContextProvider>
      </body>
    </html>
  );
}
